#! /bin/sh

for i in *.xwd
do
	base=${i%%.xwd}
	xwdtopnm < $i > $base.pnm
	pamcomp $base.pnm clear.pnm | ppmtogif > $base.gif
	rm $base.pnm
done

gifsicle --delay 1000 --loopcount=forever --optimize [0-9][0-9].gif > animation.gif
rm [0-9][0-9].gif
